export const languagesMap = new Map([
  ["af-ZA", "Afrikaans (South Africa)"],
  ["ar-AE", "Arabic (United Arab Emirates)"],
  ["ar-SA", "Arabic (Saudi Arabia)"],
  ["da-DK", "Danish (Denmark)"],
  ["de-CH", "German (Switzerland)"],
  ["de-DE", "German (Germany)"],
  ["en-AB", "English (Aruba)"],
  ["en-AU", "English (Australia)"],
  ["en-GB", "English (United Kingdom)"],
  ["en-IE", "English (Ireland)"],
  ["en-IN", "English (India)"],
  ["en-US", "English (United States)"],
  ["en-WL", "English (Wales)"],
  ["es-ES", "Spanish (Spain)"],
  ["es-US", "Spanish (United States)"],
  ["fa-IR", "Persian (Iran)"],
  ["fr-CA", "French (Canada)"],
  ["fr-FR", "French (France)"],
  ["he-IL", "Hebrew (Israel)"],
  ["hi-IN", "Hindi (India)"],
  ["id-ID", "Indonesian (Indonesia)"],
  ["it-IT", "Italian (Italy)"],
  ["ja-JP", "Japanese (Japan)"],
  ["ko-KR", "Korean (South Korea)"],
  ["ms-MY", "Malay (Malaysia)"],
  ["nl-NL", "Dutch (Netherlands)"],
  ["pt-BR", "Portuguese (Brazil)"],
  ["pt-PT", "Portuguese (Portugal)"],
  ["ru-RU", "Russian (Russia)"],
  ["ta-IN", "Tamil (India)"],
  ["te-IN", "Telugu (India)"],
  ["tr-TR", "Turkish (Turkey)"],
  ["zh-CN", "Chinese (China)"],
  ["zh-TW", "Chinese (Taiwan)"],
  ["th-TH", "Thai (Thailand)"],
  ["en-ZA", "English (South Africa)"],
  ["en-NZ", "English (New Zealand)"],
  ["vi-VN", "Vietnamese (Vietnam)"],
  ["sv-SE", "Swedish (Sweden)"],
  ["ab-GE", "Abkhazian (Georgia)"],
  ["ast-ES", "Asturian (Spain)"],
  ["az-AZ", "Azerbaijani (Azerbaijan)"],
  ["ba-RU", "Bashkir (Russia)"],
  ["be-BY", "Belarusian (Belarus)"],
  ["bg-BG", "Bulgarian (Bulgaria)"],
  ["bn-IN", "Bengali (India)"],
  ["bs-BA", "Bosnian (Bosnia and Herzegovina)"],
  ["ca-ES", "Catalan (Spain)"],
  ["ckb-IQ", "Central Kurdish (Iraq)"],
  ["ckb-IR", "Central Kurdish (Iran)"],
  ["cs-CZ", "Czech (Czech Republic)"],
  ["cy-WL", "Welsh (Wales)"],
  ["el-GR", "Greek (Greece)"],
  ["et-ET", "Estonian (Estonia)"],
  ["eu-ES", "Basque (Spain)"],
  ["fi-FI", "Finnish (Finland)"],
  ["gl-ES", "Galician (Spain)"],
  ["gu-IN", "Gujarati (India)"],
  ["ha-NG", "Hausa (Nigeria)"],
  ["hr-HR", "Croatian (Croatia)"],
  ["hu-HU", "Hungarian (Hungary)"],
  ["hy-AM", "Armenian (Armenia)"],
  ["is-IS", "Icelandic (Iceland)"],
  ["ka-GE", "Georgian (Georgia)"],
  ["kab-DZ", "Kabyle (Algeria)"],
  ["kk-KZ", "Kazakh (Kazakhstan)"],
  ["kn-IN", "Kannada (India)"],
  ["ky-KG", "Kyrgyz (Kyrgyzstan)"],
  ["lg-IN", "Ganda (Uganda)"],
  ["lt-LT", "Lithuanian (Lithuania)"],
  ["lv-LV", "Latvian (Latvia)"],
  ["mhr-RU", "Hill Mari (Russia)"],
  ["mi-NZ", "Māori (New Zealand)"],
  ["mk-MK", "Macedonian (North Macedonia)"],
  ["ml-IN", "Malayalam (India)"],
  ["mn-MN", "Mongolian (Mongolia)"],
  ["mr-IN", "Marathi (India)"],
  ["mt-MT", "Maltese (Malta)"],
  ["no-NO", "Norwegian (Norway)"],
  ["or-IN", "Odia (India)"],
  ["pa-IN", "Punjabi (India)"],
  ["pl-PL", "Polish (Poland)"],
  ["ps-AF", "Pashto (Afghanistan)"],
  ["ro-RO", "Romanian (Romania)"],
  ["rw-RW", "Kinyarwanda (Rwanda)"],
  ["si-LK", "Sinhala (Sri Lanka)"],
  ["sk-SK", "Slovak (Slovakia)"],
  ["sl-SI", "Slovenian (Slovenia)"],
  ["so-SO", "Somali (Somalia)"],
  ["sr-RS", "Serbian (Serbia)"],
  ["su-ID", "Sundanese (Indonesia)"],
  ["sw-BI", "Swahili (Burundi)"],
  ["sw-KE", "Swahili (Kenya)"],
  ["sw-RW", "Swahili (Rwanda)"],
  ["sw-TZ", "Swahili (Tanzania)"],
  ["sw-UG", "Swahili (Uganda)"],
  ["tl-PH", "Tagalog (Philippines)"],
  ["tt-RU", "Tatar (Russia)"],
  ["ug-CN", "Uighur (China)"],
  ["uk-UA", "Ukrainian (Ukraine)"],
  ["uz-UZ", "Uzbek (Uzbekistan)"],
  ["wo-SN", "Wolof (Senegal)"],
  ["zu-ZA", "Zulu (South Africa)"]
]);


